services:
  postgres:
    container_name: bankcards_db
    image: postgres:18
    env_file:
      - secret.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - bankcards_net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
      timeout: 5s
      retries: 5

  spring_boot:
    container_name: bankcards_app
    build: .
    ports:
      - '8080:8080'
    networks:
      - bankcards_net
    depends_on:
      - postgres
    env_file:
      - secret.env
    environment:
      POSTGRES_HOST: postgres
    restart: on-failure:5

networks:
  bankcards_net:
    driver: bridge

volumes:
  postgres_data: